# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 08:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import redactor.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('slug', models.SlugField(verbose_name='Ярлык')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', redactor.fields.RedactorField(verbose_name='Статья')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статии',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Ярлык')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Комменрарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='app.Article', verbose_name='Статья')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=120, verbose_name='Псевдоним')),
                ('karma', models.IntegerField(blank=True, null=True, verbose_name='Карма')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('myuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_user', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='app.MyUser', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_article', to='app.MyUser', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_article', to='app.Category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
    ]
