# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='alias',
            field=models.CharField(max_length=25, verbose_name='Псевдоним'),
        ),
    ]
