# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170627_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(max_length=450, upload_to='', verbose_name='Изображение'),
        ),
    ]
