# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170627_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='myuser',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
