# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170628_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Ярлык'),
        ),
    ]
