# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170628_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, max_length=450, upload_to='', verbose_name='Изображение'),
        ),
    ]
