# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170628_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_article', to='app.MyUser', verbose_name='Автор'),
        ),
    ]
