# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170628_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='rating',
        ),
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='alias',
            field=models.CharField(max_length=30, verbose_name='Псевдоним'),
        ),
        migrations.AddField(
            model_name='rating',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Article'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ManyToManyField(related_name='likes', to='app.MyUser'),
        ),
    ]
