# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170629_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='total_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ManyToManyField(related_name='rating', to='app.MyUser'),
        ),
    ]
